# Generated by Django 5.2.6 on 2025-10-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
