# Generated by Django 5.2.6 on 2025-10-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_demo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_video',
            field=models.FileField(blank=True, default='demo_videos/default.mp4', null=True, upload_to='demo_videos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/logo.png', null=True, upload_to='profile_pic/'),
        ),
    ]
