# Generated by Django 5.2.6 on 2025-10-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_project_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
