# Generated by Django 5.2.6 on 2025-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='permisions',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='profile_pic/'),
        ),
    ]
